### ISSUE TITLE
[jmeter-plugin] StackOverflowError on continuous usage.

### ISSUE THREAD

**Issue by mizhka** [inosion/dadagen#15]
Hi,

I've tried JMeter plugin. Here is my configuration:
  field { "accountNumber".number between 1000000 and 9999999 }.
  field { "emailAddress".template("TEST_${firstname}.${surname}@noemail.test") }.
  field { "pass".regexgen ("[1-9a-f][0-9a-f]{31}") } 

I've specified way to generate data as "Continuous". When I've tried to start 1 thread with 1 iteration, it's failed with SOE:
2016/01/25 13:33:13 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.StackOverflowError
        at scala.collection.generic.GenTraversableFactory$GenericCanBuildFrom.apply(GenTraversableFactory.scala:57)
        at scala.collection.generic.GenTraversableFactory$GenericCanBuildFrom.apply(GenTraversableFactory.scala:52)
        at scala.collection.SeqLike$class.$colon$plus(SeqLike.scala:539)
        at scala.collection.AbstractSeq.$colon$plus(Seq.scala:41)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)
        at org.inosion.dadagen.RandomDataGenerator.topoSort(RandomDataGenerator.scala:98)

I'm using OpenJDK 64bit 1.8.0.60.
I didn't try to find cause of issue, because there is lack of time and I need to switch to another task...

Thank you,
  Michael

**Comment by mizhka** [comment]
My fault - no declaration for firstname & lastname. Close it....
